version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: |
            python3 -m venv venv
            . venv/bin/activate
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
  build:
    docker:
      - image: docker:19-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - liveperson-{{ .Branch }}
      - run:
          name: Load previous image from cache
          command: |
            set +o pipefail
            docker load -i /cached-images/liveperson-twitter-search.tar | true
      - run:
          name: Build image
          command: |
            docker build --cache-from=liveperson-twitter-search --tag liveperson-twitter-search .
      - run:
          name: Save Docker image
          command: |
            mkdir -p /cached-images
            docker save -o /cached-images/liveperson-twitter-search.tar liveperson-twitter-search
      - save_cache:
          key: liveperson-{{ .Branch }}-{{ epoch }}
          paths:
            - /cached-images/liveperson-twitter-search.tar
  publish:
    docker:
      - image: docker:19-git
    steps:
      - setup_remote_docker
      - restore_cache:
          keys:
            - liveperson-{{ .Branch }}
      - run:
          name: Load previous image from cache
          command: |
            set +o pipefail
            docker load -i /cached-images/liveperson-twitter-search.tar | true
      - run:
          name: Publish image
          command: |
            docker tag liveperson-twitter-search ${DOCKER_PATH}:${CIRCLE_SHA1}
            docker login --username ${DOCKER_USERNAME} --password ${DOCKER_PASSWORD}
            docker push ${DOCKER_PATH}:${CIRCLE_SHA1}

workflows:
  publish-docker-image:
    jobs:
      - lint
      - build:
          requires:
            - lint
      - publish:
          requires:
            - build
