version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: |
            python3 -m venv venv
            . venv/bin/activate
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile
  build-and-publish:
    docker:
      - image: docker:19-git
    steps:
      - checkout
      - run:
          name: Build image
          command: docker build --tag=liveperson-twitter-search .
      - run:
          name: Publish image
          command: |
            docker tag liveperson-twitter-search $DOCKER_PATH
            docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
            docker push $DOCKER_PATH

workflows:
  publish-docker-image:
    jobs:
      - lint
      - build-and-publish:
          requires:
            - lint
