version: 2.1

jobs:
  lint:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout
      - run:
          name: Install Hadolint
          command: |
            python3 -m venv venv
            . venv/bin/activate
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

workflows:
  publish-docker-image:
    jobs:
      - lint
